### ISSUE TITLE
ÆØÅ in POST-request

### ISSUE THREAD

**Issue by mariush2** [histographer/wizard-backend#5]
ÆØÅ currently doesn't work as expected. Tried setting groupName to "på", got "p�" as response when fetching all the groups later on.

This is the POST-request on `http://localhost:9292/annotationGroup`:

`
{
 projectId: 385494,
 annotations: [],
 name: "på"
}
`

**Comment by jonwanundsen** [comment]
Can you check if it works with the latest commit?

**Comment by mariush2** [comment]
Works on the newest master.
